added better error messaging during .fhatos_completions creation.

diff --git a/bin/fhat-dev b/bin/fhat-dev
--- a/bin/fhat-dev
+++ b/bin/fhat-dev
@@ -167,9 +167,14 @@ test_esp32() {
 }
 
 build_rlwrap_completions() {
-  echo -e "[101%] ${BOLDGREEN}Analyzing CXX source to create rlwrap .fhatos_completions${NC}"
-  #   Type::singleton()->save_type(id_p(FOS_TYPE_INST_URI "from_get"), Insts::from_get(x(0)));
-  cat "${FHATOS_HOME}"/src/language/mmadt/type.hpp | grep FOS_TYPE_INST_URI | grep -o -P '(?<=FOS_TYPE_INST_URI\s").*(?="\),?(\s)Insts)' > "${FHATOS_HOME}"/bin/.fhatos_completions
+  # Type::singleton()->save_type(id_p(FOS_TYPE_INST_URI "from_get"), Insts::from_get(x(0)));
+  (cat "${FHATOS_HOME}"/src/language/mmadt/type.hpp |
+    grep FOS_TYPE_INST_URI |
+    grep -o -P '(?<=FOS_TYPE_INST_URI\s").*(?="\),?(\s)Insts)' > "${FHATOS_HOME}"/bin/.fhatos_completions &&
+    echo -e "[101%] ${BOLDGREEN}Analyzing CXX source to create rlwrap .fhatos_completions${NC}") ||
+  (echo -e "${RED}[ERROR]${NC} Regular expression failed while building ${BLUE}${FHATOS_HOME}/bin/.fhatos_completions${NC}" &&
+    exit 1;)
+
 }
 
 build_docs() {
