doc infrastructure, playing with new mmADT language parser, updated fhat-dev build utility, ...

diff --git a/bin/fhat-dev b/bin/fhat-dev
--- a/bin/fhat-dev
+++ b/bin/fhat-dev
@@ -35,52 +35,71 @@ LB="${MAGENTA}[${YELLOW}"
 RB="${MAGENTA}]${NC}"
 #############################
 
+help_menu() {
+  echo -e "usage:
+  fhat-dev {clean | test | build | upload} {esp32 | native | docs | <empty>} {<extra_args>}
+  example usasge:
+    fhat-dev clean
+    fhat-dev build docs
+    fhat-dev test native test_scheduler
+    fhat-dev build esp32 fhatos
+    fhat-dev upload esp32
+    fhat-dev upload esp32 --skip_fs
+    fhat-dev build docs
+    fhat-dev test"
+}
+
 echo -e "${FHATOS} ${MAGENTA}Development Tool${NC}"
-working_directory=$(pwd)
-if [ -z "$FHATOS_HOME" ]; then
-  echo -e " ${LB}fhatos ${RED}FHATOS_HOME=<not set>${NC}${RB}"
-  exit 1
-else
-  echo -e " ${LB}fhatos ${GREEN}FHATOS_HOME=${FHATOS_HOME}${NC}${RB}";
-  cd "${FHATOS_HOME}" || exit 1
-fi
 
-echo -e " ${LB}working directory ${GREEN}$working_directory${NC}${RB}"
-
-if [[ -z $1  ]]; then
-  filter=" "
-  echo -e " ${LB}no target${RB}"
-  exit 1
+if [[ "${2}" == "help" || "${2}" == "--help" || "${2}" == "-h" ]]; then
+  help_menu
 else
-  echo -e " ${LB}target ${GREEN}$1${NC}${RB}"
-fi
+  working_directory=$(pwd)
+  if [ -z "$FHATOS_HOME" ]; then
+    echo -e " ${LB}fhatos ${RED}FHATOS_HOME=<not set>${NC}${RB}"
+    exit 1
+  else
+    echo -e " ${LB}fhatos ${GREEN}FHATOS_HOME=${FHATOS_HOME}${NC}${RB}";
+    cd "${FHATOS_HOME}" || exit 1
+  fi
 
-if [[ -z $2 ]]; then
-  environ=" "
-  platform=" "
-  echo -e " ${LB}platform ${GREEN}all environments${NC}${RB}"
-else
-  environ="--environment $2"
-  platform="$2"
-  echo -e " ${LB}platform ${GREEN}$environ${NC}${RB}"
-fi
+  echo -e " ${LB}working directory ${GREEN}$working_directory${NC}${RB}"
 
-if [[ -z $3  ]]; then
-  filter=" "
-  echo -e " ${LB}configuration ${GREEN}<none>${NC}${RB}"
-else
-  filter="${@:3}"
-  echo -e " ${LB}configuration ${GREEN}$filter${NC}${RB}"
-fi
+  if [[ -z $1  ]]; then
+    filter=" "
+    echo -e " ${LB}no target${RB}"
+    exit 1
+  else
+    echo -e " ${LB}target ${GREEN}$1${NC}${RB}"
+  fi
 
-echo -e " ${LB}dependency ${GREEN}libpaho-mqtt-dev${NC}${RB}"
-found=$(ldconfig -p | grep -q libpaho-mqtt-dev)
-if [ ! "${found}" ]; then
-  echo -e "   libpaho-mqtt-dev ${GREEN}FOUND${NC}"
-else
-  echo -e " ${LB}libpaho-mqtt-dev${RB} ${RED}NOT FOUND${NC}"
-  sudo apt-get install -y libpaho-mqtt-dev rlwrap
-  [ $? -eq 0 ]  || exit 1
+  if [[ -z $2 ]]; then
+    environ=" "
+    platform=" "
+    echo -e " ${LB}platform ${GREEN}all environments${NC}${RB}"
+  else
+    environ="--environment $2"
+    platform="$2"
+    echo -e " ${LB}platform ${GREEN}$environ${NC}${RB}"
+  fi
+
+  if [[ -z $3  ]]; then
+    filter=" "
+    echo -e " ${LB}configuration ${GREEN}<none>${NC}${RB}"
+  else
+    filter="${@:3}"
+    echo -e " ${LB}configuration ${GREEN}$filter${NC}${RB}"
+  fi
+
+  echo -e " ${LB}dependency ${GREEN}libpaho-mqtt-dev${NC}${RB}"
+  found=$(ldconfig -p | grep -q libpaho-mqtt-dev)
+  if [ ! "${found}" ]; then
+    echo -e "   libpaho-mqtt-dev ${GREEN}FOUND${NC}"
+  else
+    echo -e " ${LB}libpaho-mqtt-dev${RB} ${RED}NOT FOUND${NC}"
+    sudo apt-get install -y libpaho-mqtt-dev rlwrap
+    [ $? -eq 0 ]  || exit 1
+  fi
 fi
 ########################################################################
 ########################################################################
@@ -253,24 +272,19 @@ elif [[ $1 == "build" ]]; then
   build_rlwrap_completions
 elif [[ $1 == "upload" ]]; then
   # clean_esp32
-  echo -e "\n${BLUE}ESP32${NC} ${FHATOS} ${BLUE}Flash Memory Partition${NC}\n"
-  printf '%b\n' "$(cat board/partition/large_code.csv)\n"
-  platformio run ${environ} --target buildfs
-  status_check $? "pio buildfs"
-  platformio run ${environ} --target uploadfs
+  if [[ $3 != "--skip_fs" ]]; then
+    echo -e "\n${BLUE}ESP32${NC} ${FHATOS} ${BLUE}Flash Memory Partition${NC}\n"
+    printf '%b\n' "$(cat board/partition/large_code.csv)\n"
+    platformio run ${environ} --target buildfs
+    status_check $? "pio buildfs"
+    platformio run ${environ} --target uploadfs
+  fi
   status_check $? "pio uploadfs"
   platformio run ${environ} --target upload
   status_check $? "pio upload"
   build_rlwrap_completions
 else
-   echo -e "usage: 
-  fhat-dev {clean | test | build | upload} {esp32 | native | <empty>} {<extra_args>}
-    fhat-dev clean
-    fhat-dev test native test_scheduler
-    fhat-dev build esp32 fhatos
-    fhat-dev upload esp32
-    fhat-dev build docs
-    fhat-dev test"
+  help_menu "${@}"
 fi
 ###### DONE
 echo -e "${GREEN}SUCCESS${NC}"
